apiVersion: v1
kind: Service
metadata:
  name: dpp-web-public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dpp-web-public
  ports:
    - name: http
      port: 80
      targetPort: http
